"""Bzlmod extension. Same shape as rules_pg / rules_temporal / rules_kind:
two tag classes — `version` (download) and `system` (host-installed).
"""

load(
    "//private:repositories.bzl",
    "playwright_system_repository",
    "playwright_version_repository",
)

_version_tag = tag_class(attrs = {
    "name": attr.string(default = "playwright"),
    "version": attr.string(mandatory = True),
})

_system_tag = tag_class(attrs = {
    "name": attr.string(default = "playwright"),
    # Optional path hint; if unset, the repo rule auto-detects via `command -v npx`.
    "npx": attr.string(default = ""),
})

def _impl(mctx):
    # Only honor tags from the root module. Without this guard, both
    # rules_playwright (when consumed as a dep) and the consumer would
    # each emit a `@playwright` repo with the same default `name`, and
    # Bazel collides them ("repo already generated by this module
    # extension"). The library's own MODULE.bazel still needs
    # `playwright.version()` / `playwright.system()` so its in-tree
    # smoke can build, but that only fires when rules_playwright
    # itself is the root.
    for mod in mctx.modules:
        if not mod.is_root:
            continue
        for tag in mod.tags.version:
            playwright_version_repository(
                name = tag.name,
                version = tag.version,
            )
        for tag in mod.tags.system:
            playwright_system_repository(
                name = tag.name,
                npx_hint = tag.npx,
            )

playwright = module_extension(
    implementation = _impl,
    tag_classes = {
        "version": _version_tag,
        "system": _system_tag,
    },
)
