"""Repository rules: download mode (`version`) and host-symlink mode (`system`).

Two-tier repo layout:
- Per-bundle child repo: holds one extracted bundle in a
  `<name>-<revision>/` subdirectory matching Playwright's cache layout.
- Hub repo: emits one `playwright_toolchain` per platform, gated on
  `target_compatible_with`, parameterised over the full bundle set.

The data lives in `private/versions.bzl`, regenerated by
`tools/update_checksums.sh`.
"""

load(":versions.bzl", "PLATFORMS", "PLAYWRIGHT_VERSIONS")

# ---- per-bundle child repo --------------------------------------------------

_BUNDLE_BUILD_TMPL = """\
load("@rules_playwright//toolchain:toolchain.bzl", "playwright_bundle")

playwright_bundle(
    name = "bundle",
    bundle_name = "{bundle_name}",
    revision = "{revision}",
    files = glob(["{dir_name}/**"]),
    visibility = ["//visibility:public"],
)
"""

def _bundle_repo_impl(rctx):
    # Extract the archive into a `<name>-<revision>/` subdirectory so the
    # repo's directory layout already matches what Playwright expects under
    # PLAYWRIGHT_BROWSERS_PATH. The browsers-root assembly action just
    # symlinks `<name>-<revision>/` from each bundle repo into one tree.
    dir_name = "{}-{}".format(rctx.attr.bundle_name, rctx.attr.revision)
    rctx.download_and_extract(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        stripPrefix = rctx.attr.strip_prefix,
        output = dir_name,
    )
    rctx.file("WORKSPACE", "workspace(name = \"{}\")\n".format(rctx.name))
    rctx.file("BUILD.bazel", _BUNDLE_BUILD_TMPL.format(
        bundle_name = rctx.attr.bundle_name,
        revision = rctx.attr.revision,
        dir_name = dir_name,
    ))

_playwright_bundle_repository = repository_rule(
    implementation = _bundle_repo_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "strip_prefix": attr.string(),
        "bundle_name": attr.string(mandatory = True),
        "revision": attr.string(mandatory = True),
    },
)

# ---- hub repo ---------------------------------------------------------------

_HUB_BUILD_TMPL = """\
load("@rules_playwright//toolchain:toolchain.bzl", "playwright_toolchain")

package(default_visibility = ["//visibility:public"])

{toolchains}
"""

_HUB_TC_TMPL = """\
playwright_toolchain(
    name = "{plat}_impl",
    version = "{version}",
    bundles = [{bundle_labels}],
)

toolchain(
    name = "{plat}",
    toolchain_type = "@rules_playwright//toolchain:playwright",
    target_compatible_with = {compat},
    toolchain = ":{plat}_impl",
)
"""

def _hub_repo_impl(rctx):
    version = rctx.attr.version
    if version not in PLAYWRIGHT_VERSIONS:
        fail("rules_playwright: unknown version '{}'. Known: {}".format(
            version,
            sorted(PLAYWRIGHT_VERSIONS.keys()),
        ))
    rctx.file("WORKSPACE", "workspace(name = \"{}\")\n".format(rctx.name))

    bundles = PLAYWRIGHT_VERSIONS[version]["bundles"]
    chunks = []
    for plat, compat in PLATFORMS.items():
        labels = []
        for bundle in bundles:
            if plat not in bundle["platforms"]:
                continue
            bundle_repo = "{}_{}_{}".format(rctx.name, bundle["name"], plat)
            # Use canonical (`@@`) form: under bzlmod, sibling repos created
            # by the same module extension are not in the hub's repo_mapping.
            labels.append('"@@{}//:bundle"'.format(bundle_repo))
        chunks.append(_HUB_TC_TMPL.format(
            plat = plat,
            version = version,
            bundle_labels = ", ".join(labels),
            compat = repr(compat),
        ))
    rctx.file("BUILD.bazel", _HUB_BUILD_TMPL.format(
        toolchains = "\n".join(chunks),
    ))

_playwright_hub_repository = repository_rule(
    implementation = _hub_repo_impl,
    attrs = {
        "version": attr.string(mandatory = True),
    },
)

# ---- public entry points (called from extensions.bzl + repositories.bzl) ----

def playwright_version_repository(name, version):
    """Materialize hub + per-bundle child repos for one Playwright version."""
    if version not in PLAYWRIGHT_VERSIONS:
        fail("rules_playwright: unknown version '{}'. Known: {}".format(
            version,
            sorted(PLAYWRIGHT_VERSIONS.keys()),
        ))
    for bundle in PLAYWRIGHT_VERSIONS[version]["bundles"]:
        for plat, src in bundle["platforms"].items():
            _playwright_bundle_repository(
                name = "{}_{}_{}".format(name, bundle["name"], plat),
                url = src["url"],
                sha256 = src["sha256"],
                strip_prefix = src["strip_prefix"],
                bundle_name = bundle["name"],
                revision = bundle["revision"],
            )
    _playwright_hub_repository(name = name, version = version)

# ---- system mode (host-installed npx) ---------------------------------------

def _system_repo_impl(rctx):
    npx = rctx.attr.npx_hint or rctx.which("npx")
    if not npx:
        fail("rules_playwright system mode: `npx` not found on PATH; pass `npx = '<path>'`.")
    rctx.symlink(npx, "npx")
    rctx.file("WORKSPACE", "workspace(name = \"{}\")\n".format(rctx.name))
    rctx.file("BUILD.bazel", """\
load("@rules_playwright//toolchain:toolchain.bzl", "playwright_toolchain")

playwright_toolchain(
    name = "system_impl",
    version = "system",
    bundles = [],  # system mode trusts the host's ~/.cache/ms-playwright
    npx = "npx",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "system",
    toolchain_type = "@rules_playwright//toolchain:playwright",
    toolchain = ":system_impl",
    visibility = ["//visibility:public"],
)
""")

playwright_system_repository = repository_rule(
    implementation = _system_repo_impl,
    attrs = {
        "npx_hint": attr.string(),
    },
    local = True,
)
