"""Generated by tools/update_checksums.sh — do not edit by hand.

Schema documented in tools/update_checksums.py.
"""

PLAYWRIGHT_VERSIONS = {
    "1.49.0": {
        "bundles": [
            {
                "name": "chromium",
                "revision": "1148",
                "platforms": {
                    "darwin_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-mac.zip",
                        "sha256": "4d8138f2d51ebfdffa7cd702106aefb5d66296009d08e0b1e01ec44cbb924984",
                        "strip_prefix": "",
                    },
                    "darwin_arm64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-mac-arm64.zip",
                        "sha256": "98e9e3c9ab6710fbc8f62aa2d4850bb664c5a2e3415b3f2858df1c64be5ef1c5",
                        "strip_prefix": "",
                    },
                    "linux_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-linux.zip",
                        "sha256": "7455d17b407bbcd1cc30c5bc8bc81fa4e67ac13635dbd5ca81f7824ec4b50439",
                        "strip_prefix": "",
                    },
                },
            },
            {
                "name": "chromium_headless_shell",
                "revision": "1148",
                "platforms": {
                    "darwin_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-mac.zip",
                        "sha256": "53a4df79b99006259a640a5716de5f7eac7d781c82cfb95c4aa8ebef9973ddc6",
                        "strip_prefix": "",
                    },
                    "darwin_arm64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-mac-arm64.zip",
                        "sha256": "ee37fe50d12019704f2b71091acea563519830a027df973ee58c03fd08103bc2",
                        "strip_prefix": "",
                    },
                    "linux_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-linux.zip",
                        "sha256": "43c8f1e29e089d9765ed83083ebbcaa7c7fe582aa762d0678f88838b55d92f63",
                        "strip_prefix": "",
                    },
                },
            },
            {
                "name": "firefox",
                "revision": "1466",
                "platforms": {
                    "darwin_amd64": {
                        "url": "https://playwright.azureedge.net/builds/firefox/1466/firefox-mac.zip",
                        "sha256": "23de219088bc89bf8b0d5583604aacb23564e2a17c0399b97c0ff97eb02fec2f",
                        "strip_prefix": "",
                    },
                    "darwin_arm64": {
                        "url": "https://playwright.azureedge.net/builds/firefox/1466/firefox-mac-arm64.zip",
                        "sha256": "937332d441fdb27d153d7557dedb4bbc4c3fa9c0f7b1f768f55dead95037034c",
                        "strip_prefix": "",
                    },
                    "linux_amd64": {
                        "url": "https://playwright.azureedge.net/builds/firefox/1466/firefox-ubuntu-22.04.zip",
                        "sha256": "7566e392e5774ab44481f6b97bd2ed252a200b961463bfcec18744fb81ecde06",
                        "strip_prefix": "",
                    },
                },
            },
            {
                "name": "webkit",
                "revision": "2104",
                "platforms": {
                    "darwin_amd64": {
                        "url": "https://playwright.azureedge.net/builds/webkit/2104/webkit-mac-14.zip",
                        "sha256": "b1c13201fa85a58728a719a7c15cd39900df1e1d0816bdf32da1063bebbdb76b",
                        "strip_prefix": "",
                    },
                    "darwin_arm64": {
                        "url": "https://playwright.azureedge.net/builds/webkit/2104/webkit-mac-14-arm64.zip",
                        "sha256": "45782f72d93f8852af2a2d5828c825256deb140fbefaeb83fd5714b285ab3582",
                        "strip_prefix": "",
                    },
                    "linux_amd64": {
                        "url": "https://playwright.azureedge.net/builds/webkit/2104/webkit-ubuntu-22.04.zip",
                        "sha256": "eca64c507763d9d22b4355c18d39087d3ceeeb31a0abf66928d59e79954a4338",
                        "strip_prefix": "",
                    },
                },
            },
        ],
    },
}

# Bundles required to support each user-facing browser type.
BROWSER_TYPE_BUNDLES = {
    "chromium": ["chromium", "chromium_headless_shell"],
    "firefox":  ["firefox"],
    "webkit":   ["webkit"],
}

PLATFORMS = {
    "darwin_amd64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx", "@platforms//cpu:arm64"],
    "linux_amd64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],
}
