"""Generated by tools/update_checksums.sh — do not edit by hand.

Schema documented in tools/update_checksums.py.
"""

PLAYWRIGHT_VERSIONS = {
    "1.49.0": {
        "bundles": [
            {
                "name": "chromium",
                "revision": "1148",
                "platforms": {
                    "darwin_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-mac.zip",
                        "sha256": "4d8138f2d51ebfdffa7cd702106aefb5d66296009d08e0b1e01ec44cbb924984",
                        "strip_prefix": "",
                    },
                    "darwin_arm64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-mac-arm64.zip",
                        "sha256": "98e9e3c9ab6710fbc8f62aa2d4850bb664c5a2e3415b3f2858df1c64be5ef1c5",
                        "strip_prefix": "",
                    },
                    "linux_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-linux.zip",
                        "sha256": "7455d17b407bbcd1cc30c5bc8bc81fa4e67ac13635dbd5ca81f7824ec4b50439",
                        "strip_prefix": "",
                    },
                },
            },
            {
                "name": "chromium_headless_shell",
                "revision": "1148",
                "platforms": {
                    "darwin_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-mac.zip",
                        "sha256": "53a4df79b99006259a640a5716de5f7eac7d781c82cfb95c4aa8ebef9973ddc6",
                        "strip_prefix": "",
                    },
                    "darwin_arm64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-mac-arm64.zip",
                        "sha256": "ee37fe50d12019704f2b71091acea563519830a027df973ee58c03fd08103bc2",
                        "strip_prefix": "",
                    },
                    "linux_amd64": {
                        "url": "https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-linux.zip",
                        "sha256": "43c8f1e29e089d9765ed83083ebbcaa7c7fe582aa762d0678f88838b55d92f63",
                        "strip_prefix": "",
                    },
                },
            },
        ],
    },
}

# Bundles required to support each user-facing browser type.
BROWSER_TYPE_BUNDLES = {
    "chromium": ["chromium", "chromium_headless_shell"],
}

PLATFORMS = {
    "darwin_amd64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx", "@platforms//cpu:arm64"],
    "linux_amd64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],
}
