#!/usr/bin/env python3
"""Refresh PLAYWRIGHT_VERSIONS in private/versions.bzl.

Fetches playwright-core@<version> from npm, reads the bundled browsers.json,
downloads each bundle for every supported platform, sha256s it, and rewrites
the manifest. The rewrite is whole-dict regeneration, not in-place patching,
so the file's structure stays clean.

Schema (matches private/versions.bzl):

    PLAYWRIGHT_VERSIONS = {
        "<playwright-version>": {
            "bundles": [
                {"name", "revision", "platforms": {"<plat>": {"url", "sha256", "strip_prefix"}}},
                ...
            ],
        },
    }

A *bundle* is a single archive that lands at
`<PLAYWRIGHT_BROWSERS_PATH>/<name>-<revision>/`. Playwright's chromium browser
type pulls multiple bundles (chromium + chromium-headless-shell, plus ffmpeg
for video recording) — they are independent units.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tarfile
import textwrap
import urllib.request
from pathlib import Path

# Bundles we need per Playwright version. v0.1.0 is chromium-only.
# Add firefox/webkit by extending this list.
WANTED_BUNDLES = ["chromium", "chromium-headless-shell"]

# Per-bundle URL templates. `%s` is the revision. Keys are bundle names from
# Playwright's browsers.json. Values are { plat: relative_url_under_cdn }.
BUNDLE_URLS = {
    "chromium": {
        "linux_amd64": "builds/chromium/%s/chromium-linux.zip",
        "darwin_amd64": "builds/chromium/%s/chromium-mac.zip",
        "darwin_arm64": "builds/chromium/%s/chromium-mac-arm64.zip",
    },
    "chromium-headless-shell": {
        "linux_amd64": "builds/chromium/%s/chromium-headless-shell-linux.zip",
        "darwin_amd64": "builds/chromium/%s/chromium-headless-shell-mac.zip",
        "darwin_arm64": "builds/chromium/%s/chromium-headless-shell-mac-arm64.zip",
    },
}

PLATFORM_CONSTRAINTS = {
    "linux_amd64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],
    "darwin_amd64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx", "@platforms//cpu:arm64"],
}

CDN = "https://playwright.azureedge.net"


def fetch_browsers_json(version: str, workdir: Path) -> dict:
    url = f"https://registry.npmjs.org/playwright-core/-/playwright-core-{version}.tgz"
    tgz = workdir / f"playwright-core-{version}.tgz"
    print(f"[fetch] {url}", file=sys.stderr)
    urllib.request.urlretrieve(url, tgz)
    with tarfile.open(tgz, "r:gz") as tf:
        member = tf.getmember("package/browsers.json")
        f = tf.extractfile(member)
        assert f is not None
        return json.load(f)


def sha256_url(url: str, dest: Path) -> str:
    print(f"[fetch] {url}", file=sys.stderr)
    with urllib.request.urlopen(url) as resp, dest.open("wb") as out:
        shutil.copyfileobj(resp, out)
    h = hashlib.sha256()
    with dest.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def revision_for(browsers_json: dict, name: str) -> str:
    for entry in browsers_json["browsers"]:
        if entry["name"] == name:
            return entry["revision"]
    raise RuntimeError(f"{name!r} not found in browsers.json")


# Bzl bundle name uses underscores (matches Playwright's runtime cache layout
# for chromium-headless-shell, where the cache dir is `chromium_headless_shell-<rev>`).
def bundle_dir_name(playwright_name: str) -> str:
    return playwright_name.replace("-", "_")


def render_manifest(versions: dict[str, dict]) -> str:
    out = [textwrap.dedent('''\
        """Generated by tools/update_checksums.sh — do not edit by hand.

        Schema documented in tools/update_checksums.py.
        """

        PLAYWRIGHT_VERSIONS = {
        ''')]
    for ver, data in sorted(versions.items()):
        out.append(f'    "{ver}": {{\n')
        out.append('        "bundles": [\n')
        for bundle in data["bundles"]:
            out.append('            {\n')
            out.append(f'                "name": "{bundle["name"]}",\n')
            out.append(f'                "revision": "{bundle["revision"]}",\n')
            out.append('                "platforms": {\n')
            for plat, p in sorted(bundle["platforms"].items()):
                out.append(f'                    "{plat}": {{\n')
                out.append(f'                        "url": "{p["url"]}",\n')
                out.append(f'                        "sha256": "{p["sha256"]}",\n')
                out.append(f'                        "strip_prefix": "{p.get("strip_prefix", "")}",\n')
                out.append('                    },\n')
            out.append('                },\n')
            out.append('            },\n')
        out.append('        ],\n    },\n')
    out.append('}\n\n')
    out.append('# Bundles required to support each user-facing browser type.\n')
    out.append('BROWSER_TYPE_BUNDLES = {\n')
    out.append('    "chromium": ["chromium", "chromium_headless_shell"],\n')
    out.append('}\n\n')
    out.append('PLATFORMS = {\n')
    for plat, c in sorted(PLATFORM_CONSTRAINTS.items()):
        out.append(f'    "{plat}": {json.dumps(c)},\n')
    out.append('}\n')
    return "".join(out)


def load_existing(manifest: Path) -> dict:
    if not manifest.exists():
        return {}
    src = manifest.read_text()
    ns: dict = {}
    try:
        exec(src.replace('"""', '#'), ns)
    except Exception:
        return {}
    return ns.get("PLAYWRIGHT_VERSIONS", {})


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("versions", nargs="+")
    ap.add_argument("--manifest", required=True, type=Path)
    ap.add_argument("--workdir", required=True, type=Path)
    args = ap.parse_args()

    table = load_existing(args.manifest)

    for version in args.versions:
        bj = fetch_browsers_json(version, args.workdir)
        bundles_out = []
        for bundle_name in WANTED_BUNDLES:
            rev = revision_for(bj, bundle_name)
            platforms = {}
            for plat, path_tmpl in BUNDLE_URLS[bundle_name].items():
                url = f"{CDN}/{path_tmpl % rev}"
                dest = args.workdir / f"{bundle_name}-{version}-{plat}.zip"
                platforms[plat] = {
                    "url": url,
                    "sha256": sha256_url(url, dest),
                    "strip_prefix": "",
                }
            bundles_out.append({
                "name": bundle_dir_name(bundle_name),
                "revision": rev,
                "platforms": platforms,
            })
        table[version] = {"bundles": bundles_out}

    args.manifest.write_text(render_manifest(table))
    print(f"[wrote] {args.manifest}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
